### ISSUE TITLE
drag and drop issue

### ISSUE THREAD

**Issue by eddydavis** [Shockfire/FiveTool#1]
results: chunk_1:(1,2): unexpected symbol near '\'

**Comment by Shockfire** [comment]
Can you explain what you're trying to do? The main FiveTool program doesn't do anything useful yet. Did you mean to use ModuleExtractor?

**Comment by eddydavis** [comment]
Ohh so that's why. Before I'd Debug FiveTools thinking that if I dropped the files there it would do the task. The part I don't understand is how to execute the ModuleExtractor.

**Comment by eddydavis** [comment]
I gave it another go and I tried to debug ModuleExtractor and it runs but it automatically shuts down

The program '[12616] ModuleExtractor.exe' has exited with code 1 (0x1).

**Comment by Shockfire** [comment]
You have to pass a path to the module file as a command-line argument. The simplest way to do this is to just drag a module file onto ModuleExtractor.exe.

**Comment by eddydavis** [comment]
I finally got it working. Thanks!
