### ISSUE TITLE
Inconsistent .Module Extraction.

### ISSUE THREAD

**Issue by LollipopLexi** [Shockfire/FiveTool#2]
.module extraction seems to be inconsistent. Many users will get different from each other, often getting different results from multiple extractions per user. 

-Extractions will often be missing files when compared to previous or later extractions.

-Even when all "known" files are extracted, MANY files will be missing any actual data (all zeroes in hex), but will be the assumed "Correct" size. This is most obvious with larger bitmap tags, but it can be observed with other tags as well. Seemingly the extraction process is creating the files at their correct size, but not generating any usable data?

**Comment by Shockfire** [comment]
Thanks for reporting. I'll add in some better error handling and then work from there.

**Comment by Shockfire** [comment]
I just made some improvements that handle some edge cases I wasn't aware of. I also added better error reporting so you'll know if extraction stops due to an error. Give it a try now.

**Comment by LollipopLexi** [comment]
So, I just tried your revision. 

-The issue with the zeroed but correct sized tags has been fixed. Known affected tags and larger bitmaps now have usable data!

-I and a few others are still having inconsistent extractions. The extraction will complete, but one person will have files that the other person doesn't, etc. 
_**Example -**_  **"globals-rtx-1__chore\pc__\objects\characters\spartan_masterchief\bitmaps    \spartan_masterchief_default\"** Will have the bitmap tags and their corresponding resource handles, but will be missing the chunk files. This is happening throughout the extract, and seems to change with every new dump attempt and differs from machine to machine for some reason.

**Comment by LollipopLexi** [comment]
So, I am hearing reports that the missing files upon extract may be due to the to-be-extracted to filepath being too long with certain files. So, if the total length of an extracted file's path is too long, it is omitted from the extraction without an error message

 This may be something worth looking into. I'm not sure if there are ways to work around it or not.

**Comment by Shockfire** [comment]
Yeah, it sounds like a [MAX_PATH](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx#maxpath) issue. There's a way around it which I can try.

In the meantime I added an error check which throws if an output file can't be opened.

**Comment by Shockfire** [comment]
Should be fixed now. Give it a shot and let me know.

I should point out though that YMMV when it comes to this, because whatever program you use to open the extracted files might not support long paths. Extracting module files near the root of your drive is still the best thing to do.

**Comment by LollipopLexi** [comment]
Everything seems to be working so far! I appreciate you taking time to help iron these things out.

Thanks.

**Comment by Shockfire** [comment]
Awesome. Thanks for the bug reports!
