### ISSUE TITLE
i cant open the module.exe file.

### ISSUE THREAD

**Issue by MasturCheef** [Shockfire/FiveTool#3]
I cant do that and i have a question how do you create a dump file of halo 5?

**Comment by MasturCheef** [comment]
Module.exe crashes on starting

**Comment by Shockfire** [comment]
It doesn't crash, you need to drag a module file onto it or else it will close immediately because it's a command-line program. I don't provide help with dumping the game, sorry, but if you look around you can probably figure something out.
