### ISSUE TITLE
Cant Read Module

### ISSUE THREAD

**Issue by Zelorous** [Shockfire/FiveTool#4]
It keeps saying "Failed to open C:\Program Files\WindowsApps\Microsoft.Halo5Forge_1.157.64802.2_x64__8wekyb3d8bbwe\deploy\pc\levels\globals-rtx-1.module for reading" and I do not understand why

**Comment by Zelorous** [comment]
Hello? Does anybody know what my problem is?... So I downloaded fivetool, visual studio community, windows sdk 8.1, the artifacts... Fivetool-master and the ModuleExtractor.exe are both on my desktop... I managed to put the globals-rtx.module onto my desktop as well... However I'm still getting the "Extraction failed: Failed to open C:\Users\Zelor\Desktop\globals-rtx-1.module for reading
Press Enter to quit..." issue and I honestly am stumped at this point

**Comment by Shockfire** [comment]
This tool isn't being maintained right now and I can't guarantee that it will work with the latest version of the game.

Also, did you dump the Halo 5 files first using a UWP dumper?

**Comment by Zelorous** [comment]
Oh sorry, I talked it some people and we got it fixed... I didn't dump the files yet and that was the issue
