### ISSUE TITLE
Appveyor releases expired

### ISSUE THREAD

**Issue by Kanken6174** [Shockfire/FiveTool#5]
Just wanted to point out that it's now impossible to get the release from appveyor for the module extractor.

It would be much appreciated if you could get at least one release working.

**Comment by EternalDusk** [comment]
I'd appreciate this as well. I unfortunately cannot build it at this point. Maybe host it on Mega or something instead of AppVeyor?

**Comment by EternalDusk** [comment]
https://www.mediafire.com/file/te0fzrvpn0hftc5/Module_Extractor.rar/file
Working ModuleExtractor build, you're welcome :D

**Comment by Kanken6174** [comment]
Perfect, thank you :D
